package protocol

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Generate produces a self-contained review bundle. Language-specific Protobuf
// binary codecs remain the responsibility of protoc and its language plugins.
func (c *Contract) Generate(dir string) error {
	ts, err := c.TypeScript()
	if err != nil {
		return err
	}
	m := c.Manifest
	m.Descriptor = "schema.pb"
	manifest, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	if err := ensureDir(dir); err != nil {
		return err
	}
	descriptor, err := proto.Marshal(c.descriptorSet(true))
	if err != nil {
		return err
	}
	gd, err := c.Godot()
	if err != nil {
		return err
	}
	wire, err := json.MarshalIndent(c.WireSchema(), "", "  ")
	if err != nil {
		return err
	}
	for _, file := range []struct {
		name string
		data []byte
	}{
		{"types.ts", ts}, {"schema.pb", descriptor}, {"contract.json", append(manifest, '\n')}, {"PROTOCOL.md", []byte(c.Markdown())}, {"protocol.gd", gd}, {"wire_schema.json", append(wire, '\n')},
	} {
		if err := atomicWrite(filepath.Join(dir, file.name), file.data); err != nil {
			return err
		}
	}
	return nil
}

func (c *Contract) reachableTypes() ([]protoreflect.MessageDescriptor, []protoreflect.EnumDescriptor) {
	var messages []protoreflect.MessageDescriptor
	var enums []protoreflect.EnumDescriptor
	seen := map[protoreflect.FullName]bool{}
	var visitEnum func(protoreflect.EnumDescriptor)
	visitEnum = func(e protoreflect.EnumDescriptor) {
		if !seen[e.FullName()] {
			seen[e.FullName()] = true
			enums = append(enums, e)
		}
	}
	var visit func(protoreflect.MessageDescriptor)
	visit = func(m protoreflect.MessageDescriptor) {
		if seen[m.FullName()] || m.IsMapEntry() {
			return
		}
		seen[m.FullName()] = true
		messages = append(messages, m)
		for i := 0; i < m.Fields().Len(); i++ {
			f := m.Fields().Get(i)
			if f.IsMap() {
				f = f.MapValue()
			}
			if f.Message() != nil {
				visit(f.Message())
			}
			if f.Enum() != nil {
				visitEnum(f.Enum())
			}
		}
	}
	for _, e := range c.Endpoints {
		visit(e.Input)
		visit(e.Output)
	}
	sort.Slice(messages, func(i, j int) bool { return messages[i].FullName() < messages[j].FullName() })
	sort.Slice(enums, func(i, j int) bool { return enums[i].FullName() < enums[j].FullName() })
	return messages, enums
}

func (c *Contract) TypeScript() ([]byte, error) {
	messages, enums := c.reachableTypes()
	// Qualification avoids most naming conflicts; explicitly reject remaining
	// collisions rather than generating duplicate TypeScript declarations.
	names := map[string]protoreflect.FullName{}
	claim := func(full protoreflect.FullName) error {
		name := tsName(full)
		if prev, ok := names[name]; ok && prev != full {
			return fmt.Errorf("TypeScript name collision: %s and %s", prev, full)
		}
		names[name] = full
		return nil
	}
	for _, m := range messages {
		if err := claim(m.FullName()); err != nil {
			return nil, err
		}
	}
	for _, e := range enums {
		if err := claim(e.FullName()); err != nil {
			return nil, err
		}
	}
	var b strings.Builder
	b.WriteString("// Generated by TabForge. ProtoJSON wire types; regenerate from the contract.\n")
	b.WriteString("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n")
	for _, e := range enums {
		var values []string
		for i := 0; i < e.Values().Len(); i++ {
			values = append(values, quote(string(e.Values().Get(i).Name())))
		}
		fmt.Fprintf(&b, "export type %s = %s | number;\n", tsName(e.FullName()), strings.Join(values, " | "))
	}
	for _, m := range messages {
		if special := wellKnown(m.FullName()); special != "" {
			fmt.Fprintf(&b, "\nexport type %s = %s;\n", tsName(m.FullName()), special)
			continue
		}
		fmt.Fprintf(&b, "\nexport type %s = {\n", tsName(m.FullName()))
		for i := 0; i < m.Fields().Len(); i++ {
			f := m.Fields().Get(i)
			if o := f.ContainingOneof(); o != nil && !o.IsSynthetic() {
				continue
			}
			fmt.Fprintf(&b, "  %s?: %s;\n", quote(f.JSONName()), tsField(f))
		}
		b.WriteString("}")
		for i := 0; i < m.Oneofs().Len(); i++ {
			o := m.Oneofs().Get(i)
			if o.IsSynthetic() {
				continue
			}
			b.WriteString(" & (\n  | {")
			for j := 0; j < o.Fields().Len(); j++ {
				fmt.Fprintf(&b, " %s?: never;", quote(o.Fields().Get(j).JSONName()))
			}
			b.WriteString(" }\n")
			for j := 0; j < o.Fields().Len(); j++ {
				f := o.Fields().Get(j)
				fmt.Fprintf(&b, "  | { %s: %s;", quote(f.JSONName()), tsField(f))
				for k := 0; k < o.Fields().Len(); k++ {
					if k != j {
						fmt.Fprintf(&b, " %s?: never;", quote(o.Fields().Get(k).JSONName()))
					}
				}
				b.WriteString(" }\n")
			}
			b.WriteString(")")
		}
		b.WriteString(";\n")
	}
	b.WriteString("\nexport interface ProtocolTypes {\n")
	for _, e := range c.Endpoints {
		fmt.Fprintf(&b, "  %s: { request: %s; response: %s };\n", quote(e.ID), tsName(e.Input.FullName()), tsName(e.Output.FullName()))
	}
	b.WriteString("}\n\nexport const operations = ")
	data, err := json.MarshalIndent(c.operations(), "", "  ")
	if err != nil {
		return nil, err
	}
	b.WriteString(strings.ReplaceAll(string(data), `"__proto__":`, `["__proto__"]:`))
	b.WriteString(" as const;\n")
	fmt.Fprintf(&b, "export const protocolVersion = %s;\n", quote(c.Manifest.Version))
	fmt.Fprintf(&b, "export const schemaHash = %s;\n", quote(c.Fingerprint()))
	schema, err := json.MarshalIndent(c.WireSchema(), "", "  ")
	if err != nil {
		return nil, err
	}
	fmt.Fprintf(&b, "export const wireSchema = %s as const;\n", strings.ReplaceAll(string(schema), `"__proto__":`, `["__proto__"]:`))
	return []byte(b.String()), nil
}

func tsName(name protoreflect.FullName) string {
	return "T_" + strings.ReplaceAll(string(name), ".", "__")
}
func quote(s string) string { data, _ := json.Marshal(s); return string(data) }

func tsField(f protoreflect.FieldDescriptor) string {
	if f.IsMap() {
		return "{ [key: string]: " + tsScalar(f.MapValue()) + " }"
	}
	if f.IsList() {
		return "Array<" + tsScalar(f) + ">"
	}
	return tsScalar(f)
}

func tsScalar(f protoreflect.FieldDescriptor) string {
	switch f.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return tsName(f.Message().FullName())
	case protoreflect.EnumKind:
		if f.Enum().FullName() == "google.protobuf.NullValue" {
			return "null"
		}
		return tsName(f.Enum().FullName())
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.StringKind, protoreflect.BytesKind,
		protoreflect.Int64Kind, protoreflect.Uint64Kind, protoreflect.Sint64Kind,
		protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind:
		return "string"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return `number | "NaN" | "Infinity" | "-Infinity"`
	default:
		return "number"
	}
}

func wellKnown(name protoreflect.FullName) string {
	switch string(name) {
	case "google.protobuf.Timestamp", "google.protobuf.Duration", "google.protobuf.FieldMask", "google.protobuf.StringValue", "google.protobuf.BytesValue", "google.protobuf.Int64Value", "google.protobuf.UInt64Value":
		return "string"
	case "google.protobuf.DoubleValue", "google.protobuf.FloatValue":
		return `number | "NaN" | "Infinity" | "-Infinity"`
	case "google.protobuf.Int32Value", "google.protobuf.UInt32Value":
		return "number"
	case "google.protobuf.BoolValue":
		return "boolean"
	case "google.protobuf.Struct":
		return "{ [key: string]: JsonValue }"
	case "google.protobuf.Value":
		return "JsonValue"
	case "google.protobuf.ListValue":
		return "JsonValue[]"
	case "google.protobuf.Any":
		return `{ "@type": string; [key: string]: JsonValue }`
	}
	return ""
}

func (c *Contract) Markdown() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\nProtocol version: `%s`; contract format: `%s`.\n\nSchema hash: `%s`.\n\n", md(c.Manifest.Name), md(c.Manifest.Version), SchemaVersion, c.Fingerprint())
	b.WriteString("Generated from Proto + manifest. All endpoints use POST with `Content-Type: application/json` and ProtoJSON request bodies. A version mismatch returns HTTP 409.\n\n")
	b.WriteString("Headers: `X-Protocol-Version` and `X-Protocol-Schema` (required by default), `X-Request-ID` (optional; server creates one if absent), and `Authorization: Bearer …` when declared. Authentication must be implemented by the application. Envelope responses also include `schemaHash`. The hash is contract identity, not authentication. Generated `wireSchema` validates ProtoJSON fields in TypeScript and Godot.\n\n")
	b.WriteString("ProtoJSON uses lowerCamelCase (or explicit json_name), decimal strings for 64-bit integers, base64 bytes, enum names, omitted defaults, and at most one member per oneof. Typescript types describe the emitted wire shape, not binary Protobuf objects.\n\n")
	for _, e := range c.Endpoints {
		fmt.Fprintf(&b, "## %s\n\n- Route: `POST %s`\n- Transport: `%s`\n- Auth: `%s`\n- Timeout: %d ms (whole request/stream)\n- RPC: `%s`\n- Request: `%s`\n- Response: `%s`\n\n", md(e.ID), e.Path, e.Transport, e.Auth, e.TimeoutMS, e.RPC, e.Input.FullName(), e.Output.FullName())
		if e.Transport == "http_json" {
			b.WriteString("Success: `{\"protocolVersion\":\"…\",\"schemaHash\":\"…\",\"requestId\":\"…\",\"data\":{…}}`. Failures use a non-2xx status and an `error` member instead of `data`.\n\n")
		} else {
			b.WriteString("Response: `text/event-stream`. Each SSE `data` is `{\"protocolVersion\":\"…\",\"schemaHash\":\"…\",\"requestId\":\"…\",\"sequence\":\"1\",\"payload\":{…}}`. Sequence starts at 1 and increments by 1; SSE `id` is the same decimal string. `payload` is the full response oneof message, not only its nested member.\n\n| SSE event | Proto field | Payload type | Terminal |\n| --- | --- | --- | --- |\n")
			for _, ev := range e.Events {
				f := e.Output.Fields().ByName(protoreflect.Name(ev.Field))
				fmt.Fprintf(&b, "| %s | %s | %s | %t |\n", ev.Name, f.JSONName(), f.Message().FullName(), ev.Terminal)
			}
			b.WriteString("\nA terminal event ends the stream. An EOF before a terminal event is a failure. Transport failures after headers use the reserved terminal `protocol.error` event with `error` instead of `payload`. Cancelling the client aborts the request; it does not imply provider-side work was cancelled. No automatic retries or replay are promised in v1.\n\n")
		}
	}
	b.WriteString("## Errors\n\n`error` has `{ code: string, message: string, retryable: boolean }`. Business errors belong in declared Proto messages/events. Transport codes: `bad_request`, `request_too_large`, `not_found`, `method_not_allowed`, `unsupported_media_type`, `unauthorized`, `version_mismatch`, `schema_mismatch`, `timeout`, `internal`, `incomplete_stream`. Limits default to 1 MiB per request/response/frame. SSE comments provide keepalive without consuming event sequence. Go handlers must respect context cancellation. Deploy using `httptransport.HTTPServer` and an explicit CORS origin allowlist where needed.\n")
	messages, enums := c.reachableTypes()
	b.WriteString("\n## Message types\n\nFields may be omitted according to ProtoJSON presence/default rules. `oneof` members are mutually exclusive.\n")
	for _, m := range messages {
		fmt.Fprintf(&b, "\n### %s\n\n", m.FullName())
		if comment := sourceComment(m); comment != "" {
			fmt.Fprintf(&b, "%s\n\n", md(comment))
		}
		if special := wellKnown(m.FullName()); special != "" {
			fmt.Fprintf(&b, "Well-known ProtoJSON representation: `%s`.\n", special)
			continue
		}
		b.WriteString("| JSON field | Proto type | JSON / TS wire type | Presence | Description |\n| --- | --- | --- | --- | --- |\n")
		for i := 0; i < m.Fields().Len(); i++ {
			f := m.Fields().Get(i)
			presence := "default may be omitted"
			if f.HasPresence() {
				presence = "explicit presence"
			}
			if f.IsList() || f.IsMap() {
				presence = "empty may be omitted"
			}
			if o := f.ContainingOneof(); o != nil && !o.IsSynthetic() {
				presence = "oneof " + string(o.Name())
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", md(f.JSONName()), protoFieldType(f), md(tsField(f)), presence, md(sourceComment(f)))
		}
	}
	for _, e := range enums {
		fmt.Fprintf(&b, "\n### %s\n\n| Name | Number |\n| --- | --- |\n", e.FullName())
		for i := 0; i < e.Values().Len(); i++ {
			v := e.Values().Get(i)
			fmt.Fprintf(&b, "| %s | %d |\n", v.Name(), v.Number())
		}
	}
	b.WriteString("\nWire mapping: [official ProtoJSON specification](https://protobuf.dev/programming-guides/json/). Framing: [WHATWG SSE specification](https://html.spec.whatwg.org/multipage/server-sent-events.html).\n")
	return b.String()
}

func protoFieldType(f protoreflect.FieldDescriptor) string {
	if f.IsMap() {
		return "map<" + protoFieldType(f.MapKey()) + ", " + protoFieldType(f.MapValue()) + ">"
	}
	typeName := f.Kind().String()
	if f.Message() != nil {
		typeName = string(f.Message().FullName())
	}
	if f.Enum() != nil {
		typeName = string(f.Enum().FullName())
	}
	if f.IsList() {
		typeName = "repeated " + typeName
	}
	return typeName
}

func sourceComment(desc protoreflect.Descriptor) string {
	var path []int32
	for current := desc; current != nil; current = current.Parent() {
		var number int32
		switch current.(type) {
		case protoreflect.MessageDescriptor:
			if _, nested := current.Parent().(protoreflect.MessageDescriptor); nested {
				number = 3
			} else {
				number = 4
			}
		case protoreflect.FieldDescriptor:
			number = 2
		case protoreflect.FileDescriptor:
			locations := current.(protoreflect.FileDescriptor).SourceLocations()
			for i := 0; i < locations.Len(); i++ {
				location := locations.Get(i)
				if len(path) != len(location.Path) {
					continue
				}
				match := true
				for j := range path {
					if path[j] != location.Path[j] {
						match = false
						break
					}
				}
				if match {
					return strings.TrimSpace(location.LeadingComments + " " + location.TrailingComments)
				}
			}
			return ""
		default:
			return ""
		}
		path = append([]int32{number, int32(current.Index())}, path...)
	}
	return ""
}

func md(s string) string {
	return strings.NewReplacer("\n", " ", "\r", " ", "`", "", "#", "", "|", "\\|").Replace(s)
}
