package protocol

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

type WireSchema struct {
	Messages map[string]MessageShape `json:"messages"`
	Enums    map[string][]string     `json:"enums"`
}
type MessageShape struct {
	Fields map[string]FieldShape `json:"fields"`
	Oneofs [][]string            `json:"oneofs,omitempty"`
}
type FieldShape struct {
	Kind     string `json:"kind"`
	Type     string `json:"type,omitempty"`
	List     bool   `json:"list,omitempty"`
	MapKey   string `json:"mapKey,omitempty"`
	Required bool   `json:"required,omitempty"`
}

func (c *Contract) WireSchema() WireSchema {
	s := WireSchema{Messages: map[string]MessageShape{}, Enums: map[string][]string{}}
	var messages []protoreflect.MessageDescriptor
	var enums []protoreflect.EnumDescriptor
	var collect func(protoreflect.MessageDescriptors)
	collect = func(list protoreflect.MessageDescriptors) {
		for i := 0; i < list.Len(); i++ {
			m := list.Get(i)
			if !m.IsMapEntry() {
				messages = append(messages, m)
			}
			for j := 0; j < m.Enums().Len(); j++ {
				enums = append(enums, m.Enums().Get(j))
			}
			collect(m.Messages())
		}
	}
	c.Files.RangeFiles(func(f protoreflect.FileDescriptor) bool {
		collect(f.Messages())
		for i := 0; i < f.Enums().Len(); i++ {
			enums = append(enums, f.Enums().Get(i))
		}
		return true
	})
	for _, e := range enums {
		values := []string{}
		for i := 0; i < e.Values().Len(); i++ {
			values = append(values, string(e.Values().Get(i).Name()))
		}
		s.Enums[string(e.FullName())] = values
	}
	for _, m := range messages {
		shape := MessageShape{Fields: map[string]FieldShape{}}
		for i := 0; i < m.Fields().Len(); i++ {
			f := m.Fields().Get(i)
			value := f
			if f.IsMap() {
				value = f.MapValue()
			}
			field := FieldShape{Kind: value.Kind().String(), List: f.IsList(), Required: f.Cardinality() == protoreflect.Required}
			if f.IsMap() {
				field.MapKey = f.MapKey().Kind().String()
			}
			if value.Message() != nil {
				field.Type = string(value.Message().FullName())
			}
			if value.Enum() != nil {
				field.Type = string(value.Enum().FullName())
			}
			shape.Fields[f.JSONName()] = field
		}
		for i := 0; i < m.Oneofs().Len(); i++ {
			o := m.Oneofs().Get(i)
			if o.IsSynthetic() {
				continue
			}
			fields := []string{}
			for j := 0; j < o.Fields().Len(); j++ {
				fields = append(fields, o.Fields().Get(j).JSONName())
			}
			shape.Oneofs = append(shape.Oneofs, fields)
		}
		s.Messages[string(m.FullName())] = shape
	}
	return s
}

func (c *Contract) descriptorSet(comments bool) *descriptorpb.FileDescriptorSet {
	set := &descriptorpb.FileDescriptorSet{}
	c.Files.RangeFiles(func(f protoreflect.FileDescriptor) bool {
		p := protodesc.ToFileDescriptorProto(f)
		if !comments {
			p.SourceCodeInfo = nil
		}
		set.File = append(set.File, p)
		return true
	})
	sort.Slice(set.File, func(i, j int) bool { return set.File[i].GetName() < set.File[j].GetName() })
	return set
}

// Fingerprint identifies an exact contract and descriptor bundle, excluding
// source comments and the filesystem path of the descriptor.
func (c *Contract) Fingerprint() string {
	m := c.Manifest
	m.Descriptor = ""
	manifest, _ := json.Marshal(m)
	schema, _ := proto.MarshalOptions{Deterministic: true}.Marshal(c.descriptorSet(false))
	h := sha256.New()
	h.Write(manifest)
	h.Write([]byte{0})
	h.Write(schema)
	return hex.EncodeToString(h.Sum(nil))
}

// Godot emits resource-local metadata without global class_name registrations.
// The runtime validates Dictionaries against the same schema as TypeScript.
func (c *Contract) Godot() ([]byte, error) {
	data, err := c.RuntimeJSON("\t")
	if err != nil {
		return nil, err
	}
	return []byte(fmt.Sprintf("# Generated by TabForge. Do not edit.\nextends RefCounted\n\nconst CONTRACT: Dictionary = %s\n", data)), nil
}

// RuntimeJSON is the language-neutral contract loaded by native SDKs.
func (c *Contract) RuntimeJSON(indent string) ([]byte, error) {
	return json.MarshalIndent(map[string]interface{}{"version": c.Manifest.Version, "schemaHash": c.Fingerprint(), "operations": c.operations(), "wireSchema": c.WireSchema()}, "", indent)
}

type operation struct {
	Path         string                 `json:"path"`
	Transport    string                 `json:"transport"`
	Auth         string                 `json:"auth"`
	TimeoutMS    int                    `json:"timeoutMS"`
	RequestType  string                 `json:"requestType"`
	ResponseType string                 `json:"responseType"`
	Events       map[string]interface{} `json:"events,omitempty"`
}

func (c *Contract) operations() map[string]operation {
	ops := map[string]operation{}
	for _, e := range c.Endpoints {
		o := operation{Path: e.Path, Transport: e.Transport, Auth: e.Auth, TimeoutMS: e.TimeoutMS, RequestType: string(e.Input.FullName()), ResponseType: string(e.Output.FullName())}
		if len(e.Events) != 0 {
			o.Events = map[string]interface{}{}
			for _, ev := range e.Events {
				f := e.Output.Fields().ByName(protoreflect.Name(ev.Field))
				o.Events[ev.Name] = map[string]interface{}{"field": f.JSONName(), "terminal": ev.Terminal}
			}
		}
		ops[e.ID] = o
	}
	return ops
}
